name: Python Distribution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          architecture: 'x64' 
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile GUI
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: gui.py
          enable-plugins: tk-inter
          windows-icon-from-ico: assets/kozmadeus.ico
          include-package: modules
          disable-console: true
          enable-console: false
          mode: standalone

      - name: Compile CLI
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: cli.py
          windows-icon-from-ico: assets/kozmadeus.ico
          include-package: modules
          standalone: true
          onefile: false

      - name: Prepare Compiled Distributions
        run: |
          mkdir build/artifact/Kozmadeus
          echo Merging CLI and GUI into one artifact...
          Copy-Item -Force build/cli.dist/* build/artifact/Kozmadeus
          Copy-Item -Force build/gui.dist/* build/artifact/Kozmadeus
          Rename-Item build/artifact/Kozmadeus/gui.exe kozmadeus-gui.exe
          Rename-Item build/artifact/Kozmadeus/cli.exe kozmadeus-cli.exe
          echo Appending necessary assets... 
          Copy-Item -Force -Recurse assets build/artifact/Kozmadeus
          Copy-Item -Force -Recurse templates build/artifact/Kozmadeus
          Copy-Item -Force -Recurse docs build/artifact/Kozmadeus
          Copy-Item README.md build/artifact/Kozmadeus
          Copy-Item LICENSE.md build/artifact/Kozmadeus

      # Uploads artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build (windows-latest)
          path: build/artifact
